services:
  postgres:
    image: postgres:15
    container_name: kanban_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: kanban
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kanban-network

networks:
  kanban-network:

volumes:
  postgres_data: