name: Go CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build, Lint, Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy

      - name: Lint
        run: golangci-lint run

      - name: Run tests
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - name: Check for formatting
        run: gofmt -s -l . | tee /dev/stderr | wc -l | grep '^0$' || exit 1